server: 
    session: 
        timeout: 1800
#    port: 9090



spring:
    thymeleaf:
        cache: false
        suffix: .html
        mode: HTML5
        encoding: utf-8
        content-type: text/html
    datasource:
        name: etrip
        url: jdbc:mysql://localhost:3306/etrip?characterEncoding=UTF-8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒 
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小 
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20

# HTTP ENCODING
http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true

# view
mvc:
    view:
        prefix: /WEB-INF/view/
        suffix: .jsp



# MyBatis
mybatis:
    # 配置类型别名
    typeAliasesPackage: cn.etrip.entity
    # dao层接口
    basePackage: cn.etrip.mapper
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/mapper/*.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml



# LOGGING
logging:
    level:
        cn.91etrip.dao: DEBUG
    config: classpath:logback-spring.xml


etrip:
  getFilePath: http://ogez3quhp.bkt.clouddn.com

